#!/bin/sh

[ "$(id -u)" -eq 0 ] && exit 1

xargs yay -S --noconfirm --disable-download-timeout --needed \
	<"$HOME/.dotfiles/assets/packages/opt/music"

# Instalar lrcput
LRCPUT_TARGET="$HOME/.local/bin/lrcput"
# Crear el directorio donde guardar el script
mkdir -p "$HOME/.local/bin"
# Descargar el script
wget -q "https://raw.githubusercontent.com/JustOptimize/lrcput/refs/heads/main/lrcput.py" -O "$LRCPUT_TARGET"
# Añadir un shebang indicando que es un script de python
sed -i '1i #!/usr/bin/python' "$LRCPUT_TARGET"
# Hacer el script ejecutable
chmod +x "$LRCPUT_TARGET"
