#!/bin/bash

# Script para configurar libvirt de forma que nuestro usuario pueda usar
# virt-manager sin tener que introducir la contraseña cada vez

[ "$(id -u)" -eq 0 ] && exit 1

# Instalar y configurar libvirt
virt_install() {
	xargs yay -S --noconfirm --disable-download-timeout --needed \
		<"$HOME/.dotfiles/assets/packages/opt/virt"

	sudo install -m 755 "$HOME/.dotfiles/assets/desktop/looking-glass-client.desktop" \
		/usr/local/share/applications/looking-glass-client.desktop

	# Configurar QEMU para usar el usuario actual
	sudo sed -i "s/^#user = .*/user = \"$USER\"/" /etc/libvirt/qemu.conf
	sudo sed -i "s/^#group = .*/group = \"$USER\"/" /etc/libvirt/qemu.conf

	# Configurar libvirt
	sudo sed -i "s/^#unix_sock_group = .*/unix_sock_group = \"$USER\"/" \
		/etc/libvirt/libvirtd.conf
	sudo sed -i "s/^#unix_sock_rw_perms = .*/unix_sock_rw_perms = \"0770\"/" \
		/etc/libvirt/libvirtd.conf

	# Agregar el usuario a los grupos necesarios para la virtualización
	sudo usermod -aG libvirt,libvirt-qemu,kvm "$USER"

	# Activar los servicios necesarios
	sudo systemctl enable libvirtd
	sudo systemctl enable virtlogd
}

# Desinstalar libvirt por completo
virt_uninstall() {
	# Detener servicios
	sudo systemctl disable libvirtd --now
	sudo systemctl disable virtlogd --now

	# Borrar al usuario de los grupos
	for GROUP in libvirt libvirt-qemu kvm; do
		sudo gpasswd -d "$USER" $GROUP
	done

	# Desinstalar los paquetes
	xargs yay -Rcns --noconfirm \
		<"$HOME/.dotfiles/assets/packages/opt/virt"

	# Borrar archivos restantes
	sudo rm -rf /var/lib/libvirt
	sudo rm -rf /etc/libvirt
	sudo rm -f /usr/local/share/applications/looking-glass-client.desktop

	sync
}

if [ "$1" = "uninstall" ]; then
	virt_uninstall >/dev/null 2>&1
else
	virt_install
fi
