#!/bin/bash

# Script para configurar el reloj de hardware y sincronizalo con la hora
# del sistema.

# Se termina la ejecución de toda la tubería despúes del primer fallo
set -o pipefail

[ "$(id -u)" -ne 0 ] && exit 1

# Obtener la zona horaria actual
TIMEZONE="$(readlink -f /etc/localtime | sed 's|.*/zoneinfo/||')"

# Verificar dependencias
if ! command -v jq &>/dev/null; then
	echo "Error: jq no está instalado." >&2
	exit 1
fi

# Inicializar variables
COUNTER=1
CURRENT_TIME=""

# Función para obtener la hora desde una API
get_current_time() {
	timeout -k 1s 10s curl -s \
		"https://timeapi.io/api/Time/current/zone?timeZone=$TIMEZONE" |
		grep -oP '"dateTime":"\K[^"]+' | cut -d. -f1 | sed 's/T/ /'
}

# Intentar obtener la hora hasta que se defina o se alcance el límite de intentos
while [ -z "$CURRENT_TIME" ] && [ "$COUNTER" -le 5 ]; do
	echo "Intento $COUNTER: Obteniendo la hora..."

	# Primero intentar con worldtimeapi
	CURRENT_TIME=$(get_current_time)

	# Incrementar el contador y esperar antes del siguiente intento
	if [ -z "$CURRENT_TIME" ]; then
		COUNTER=$((COUNTER + 1))
		sleep 5
	fi
done

# Comprobar si se obtuvo la hora correctamente
if [ -z "$CURRENT_TIME" ]; then
	echo "Error: No se pudo obtener la hora después de 5 intentos." >&2
	exit 1
fi

echo "Hora obtenida: $CURRENT_TIME"

# Configurar el reloj de hardware y sincronizar con el sistema
if ! hwclock --set --date="$CURRENT_TIME"; then
	echo "Error: No se pudo configurar el reloj de hardware." >&2
	exit 1
fi

if ! hwclock --hctosys; then
	echo "Error: No se pudo sincronizar el reloj del sistema con el reloj de hardware." >&2
	exit 1
fi

echo "Reloj de hardware y sistema sincronizados correctamente."
