#!/bin/bash

[ "$(id -u)" -eq 0 ] && exit 1

# Activar servicio
service_add() {
	sudo systemctl enable "$1"
}
# Activar servicio para el usuario
user_service_add() {
	systemctl --user enable "$1"
}

[ "$(id -u)" -eq 0 ] && exit 1

SERVICES=(
	"earlyoom"
	"fwupd"
	"syslog-ng"
	"tlp"
	"xdm"
)

USER_SERVICES=(
	"dbus"
	"pipewire"
	"pipewire-pulse"
	"wireplumber"
)

# Activar los servicios del sistema
for SERVICE in "${SERVICES[@]}"; do
	service_add "$SERVICE"
done
# Activar los servicios del usuario
for USER_SERVICE in "${USER_SERVICES[@]}"; do
	user_service_add "$USER_SERVICE"
done
