#!/bin/bash

# Script que crea enlaces simbólicos en /usr/local/bin para ciertos scripts
# - Invocado por /update.sh

[ "$(id -u)" -eq 0 ] && exit 1

files=(
	"rdp-connect"
	"tray-toggle"
	"wakeat"
	"wakeme"
)
for file in "${files[@]}"; do
	sudo ln -sf "$HOME/.dotfiles/assets/bin/$file" "/usr/local/bin/$file"
done
