#!/bin/sh

[ -f "$HOME/.config/Xresources" ] && xrdb "$HOME/.config/Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		# shellcheck source=/dev/null
		[ -x "$f" ] && "$f" &
	done
fi

while true; do dwm; done
